### ISSUE TITLE
EmbeddedQuery fails to execute in workbench 

### ISSUE THREAD

**Issue by navroudsari** [controlm/workbench#5] opened 2023-05-05 17:21 UTC
Hi, 

I'm unable to execute embedded queries because it looks like there is a problem with AP server failing.   

I've configured a connection profile that points to our oracle host.  All connections to the DB host/port are reachable.  The connection profile has been validated.

Tested with Control-M workbench 9.21.105 and 9.21.110.  Running via Docker on RHEL8.5.

In the apmanager.log I see:

> 2023-05-05 17:07:21,865 INFO [id301] (StatusCommandRunner:76) - The deployment directory: /home/workbench/ctm_agent/ctm/cm/AP/apweb/webapps 
> 2023-05-05 17:07:21,865 INFO [id301] (StatusCommandRunner:77) - With verbose: No 
> 2023-05-05 17:07:21,865 INFO [id301] (OneParamsManager:122) - Read ApplicationPack properties file 
> 2023-05-05 17:07:21,866 INFO [id301] (OneParamsManager:156) - Content of properties: {RecoveryMaxRetry=18, CM_DIR=/home/workbench/ctm_agent/ctm/cm/AP/exe, MIN_SUPPORTED_AGENT_VERSION=9.0.18.000, ENCRYPTION_TYPE=2, AG_DIR=/home/workbench/ctm_agent/ctm, curlVersion=7.44.0, AP_JAVA_HOME=/home/workbench/external_java, CM_LIB_NAME=AP, CMVER=921000, PREV_ENCRYPTION_TYPE=0, PREV_CMVER=000000, agent.logs=/home/workbench/ctm_agent/ctm/proclog, TOMCAT_PORT=39580, RecoveryRetrySleepTime=10000, SECONDS_BETWEEN_START_CHECKS=30, IPP_ROLLBACK_DIR=/home/workbench/ctm_agent/ctm/cm/AP/ipp/rollback, PACKAGE_DATE=Aug-11-2022, OFFICIAL_RELEASE=9.0.21.000, AMOUNT_START_CHECKS=6, PERL_EXEC=/home/workbench/bmcperl/bmcperl_V1/perl} 
> 2023-05-05 17:07:21,866 INFO [id301] (StatusCommandRunner:149) - Check if the dispatcher war is delpoyed 
> 2023-05-05 17:07:21,866 INFO [id301] (StatusCommandRunner:160) - The dispacher isn't deployed 
> 2023-05-05 17:07:21,866 INFO [id301] (StatusCommandRunner:121) - Control-M Application Pack Server is not running 
> 2023-05-05 17:07:21,866 INFO [id301] (StatusCommandRunner:126) - Finish checking the status of the tomcat server 
> 2023-05-05 17:07:21,866 INFO [id301] (CheckStartCommandRunner:114) - Try to stop the server after the starting weren't finished well. See catalina logs for more information 
> 2023-05-05 17:07:21,867 INFO [id301] (TomcatStopper:97) - Try to stop the server 
> 2023-05-05 17:07:21,867 INFO [id301] (TomcatStopper:218) - Invoke Bootstrap.stop() 
> 2023-05-05 17:07:21,958 WARN [id301] (TomcatStopper:254) - Found an exception in the output. To see it, change log level of agent to 'DEBUG' 
> 2023-05-05 17:07:21,958 INFO [id301] (TomcatStopper:282) - Makes sure that the tomcat is down. Runs the kill script: '/bin/bash /home/workbench/ctm_agent/ctm/cm/AP/exe/stop_web_server /home/workbench/ctm_agent/ctm/cm/AP/apweb' 
> 2023-05-05 17:07:21,991 INFO [id301] (TomcatStopper:207) - Control-M Application Pack Server successfully shutdown 
> 2023-05-05 17:07:21,991 INFO [id301] (TomcatStopper:209) - Finish the trying to stop the server 
> 2023-05-05 17:07:21,991 INFO [id301] (CheckStartCommandRunner:94) - **Control-M Application Pack Server failed to start.** 
> 2023-05-05 17:07:21,992 INFO [id301] (ApManagerMain:71) - The command return code is: 1 

Any ideas?

**Comment by jfink5** [comment] 2023-06-29 18:39
When running an embedded script Job on either workbench or external agent, then it fails with following output.

/bin/bash: line 1: /home/ec2-user/ctm/runtime/INSTREAM_00004_0002_myscript.py: cannot execute: required file not found

That temporary script is not getting set with executable permissions.  I could not reproduce this in an on prem v21.100 environment.

**Comment by rbeker-BMC** [comment] 2023-08-29 06:23
We just released a new workbench which is based on v21.100. 
It includes a fix for this bug.
Can you try and confirm it is closed?

**Comment by navroudsari** [comment] 2023-09-25 15:09
Thanks, I'll try to take a look soon and feed back.  Appreciate your efforts.

**Closed as completed** 2023-11-12 13:26 UTC
Labels: Under Research
